### ISSUE TITLE
Azure: Template Base URL in Sample for Technical Service not valit any more

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app#31]
**Version Info**
PRIVATE-BUILD-ON-18c04074cb562019/06/18
**Describe the bug**
Sample for Technical Service not correct:
 ParameterDefinition configurable="true" default="https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/" id="TEMPLATE_BASE_URL" 

log- file:
 2019-06-26 07:48:18,955 [EjbTimerPool - 1] - ERROR - Get template failed. url='https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/        resources/SampleTemplate.json' operation='create'
  20552 java.io.FileNotFoundException: https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/SampleTemplate.json
  20553         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
  20554         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
  20555         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
  20556         at org.oscm.app.azure.AzureCommunication.getBOMInputStream(AzureCommunication.java:273)
  20557         at org.oscm.app.azure.AzureCommunication.getTemplate(AzureCommunication.java:253)
  20558         at org.oscm.app.azure.AzureCommunication.deploymentTemplate(AzureCommunication.java:776)
  20559         at org.oscm.app.azure.AzureCommunication.createInstance(AzureCommunication.java:391)
  20560         at org.oscm.app.azure.controller.Dispatcher.dispatchProvisioningProcess(Dispatcher.java:210)
  20561         at org.oscm.app.azure.controller.Dispatcher.dispatch(Dispatcher.java:126)
  20562         at org.oscm.app.azure.controller.AzureController.getInstanceStatus(AzureController.java:220)
  20563

**Comment by elfriedegoetz** [comment]
The sample is now changed correctly
